### ISSUE TITLE
服务意外停止

### ISSUE THREAD

**Issue by sf467** [chiyuki0325/PlasmaDesktopLyrics#3]
可以正常使用一段时间，但总会意外停止
![图片](https://github.com/chiyuki0325/PlasmaDesktopLyrics/assets/121373973/79f89e2c-a2c1-43c3-af73-ed0fe5a187f9)

```
× plasma-desktop-lyrics.service - Plasma Desktop Lyrics daemon
     Loaded: loaded (/home/sf467/.config/systemd/user/plasma-desktop-lyrics.service; 
enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-03-23 21:01:09 CST; 1min 37s ago
   Duration: 2h 17min 53.277s
    Process: 836 ExecStart=/home/sf467/.local/bin/plasma-desktop-lyrics-daemon (code=exited, status=2)
   Main PID: 836 (code=exited, status=2)
        CPU: 1min 720ms

3月 23 18:43:22 Analyse plasma-desktop-lyrics-daemon[836]: 有新的连接
3月 23 21:01:09 Analyse plasma-desktop-lyrics-daemon[836]: panic: runtime error: index out of range [0] with length 0
3月 23 21:01:09 Analyse plasma-desktop-lyrics-daemon[836]: goroutine 7 [running]:
3月 23 21:01:09 Analyse plasma-desktop-lyrics-daemon[836]: main.updateLyrics()
3月 23 21:01:09 Analyse plasma-desktop-lyrics-daemon[836]:         /home/sf467/PlasmaDesktopLyrics/main.go:279 +0x35e
3月 23 21:01:09 Analyse plasma-desktop-lyrics-daemon[836]: created by main.main in goroutine 1
3月 23 21:01:09 Analyse plasma-desktop-lyrics-daemon[836]:         /home/sf467/PlasmaDesktopLyrics/main.go:60 +0xa8
3月 23 21:01:09 Analyse systemd[823]: plasma-desktop-lyrics.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
3月 23 21:01:09 Analyse systemd[823]: plasma-desktop-lyrics.service: Failed with result 'exit-code'.
3月 23 21:01:09 Analyse systemd[823]: plasma-desktop-lyrics.service: Consumed 1min 720ms CPU time, 19.1M memory peak, 28.0K memory swap peak.
```

**Comment by sf467** [comment]
而且重启服务之后挂件也不能正常运行

**Comment by sf467** [comment]
问了bing,似乎是因为歌词文件是空文件，因为我那首歌是纯音乐

**Comment by sf467** [comment]
把bing的代码加进去似乎不起作用，给所有的纯音乐的lrc文件加入了
[00:00.00]此歌曲为没有填词的纯音乐，请您欣赏
这一句，问题解决了

**Comment by chiyuki0325** [comment]
可能已在 8f49f096bc29af5aa6ee0b9643d6157a096a32dc 修复。

https://github.com/chiyuki0325/PlasmaDesktopLyrics/assets/73830635/20ea7486-446b-41ca-947a-4d764daf7fa6
